### exam-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: port-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: port-app
  template:
    metadata:
      labels:
        app: port-app
    spec:
      containers:
      - name: port-app
        image: ghcr.io/starburn-hub/port-app

        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: port-app
  namespace: default

spec:
  selector:
    app: port-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

##### END OF exam-app.yaml
